#version 450

#include "dequant_head.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout (binding = 0) readonly buffer A {block_q2_0_g128 data_a[];};
layout (binding = 1) writeonly buffer D {D_TYPE data_b[];};

void main() {
    const uint i   = gl_WorkGroupID.x * 4 + gl_LocalInvocationID.x / 64;
    const uint tid = gl_LocalInvocationID.x % 64;
    const uint il  = tid / 4;
    const uint ir  = tid % 4;
    const uint ib  = 4*i + ir;
    if (ib >= p.nel / QUANT_K_Q2_0_G128) {
        return;
    }

    const uint b_idx = 512*i + QUANT_K_Q2_0_G128*ir + 8*il;

    const float d  = float(data_a[ib].d);
    const uint  b0 = uint(data_a[ib].qs[il*2    ]);
    const uint  b1 = uint(data_a[ib].qs[il*2 + 1]);

    [[unroll]] for (uint l = 0; l < 4; ++l) {
        data_b[b_idx + l    ] = D_TYPE(float(int((b0 >> (l*2u)) & 3u) - 1) * d);
        data_b[b_idx + l + 4] = D_TYPE(float(int((b1 >> (l*2u)) & 3u) - 1) * d);
    }
}
